title: 'paranoia'
description: Music Producer/Sound designer
remote_theme: n1n4-303/jekyll-theme-console

header_pages:
  - README.md
  - tutorials.md
  - music.md
  - resume.md

footer: 'follow me on <a href="https://twitter.com/nvie1ra">twitter</a> <a href="https://soundcloud.com/djparanoia">soundcloud</a>'
