title: 'paranoia'
description: Music Producer/Sound designer
remote_theme: b2a3e8/jekyll-theme-console

header_pages:
  - README.md
  - tutorials.md
  - music.md
  - resume.md

footer: 'follow me on <a href="https://twitter.com/djparanoiaprod">twitter</a>'
